[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = []

[rpc_endpoints]
etherlink_testnet="https://node.ghostnet.etherlink.com"

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
