[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.RPC_URL]
arb_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
