[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = []

[rpc_endpoints]
core_testnet="https://rpc.test2.btcs.network"

[etherscan]
core_testnet = { key = "${CORESCAN_API_KEY}", url = "https://api.test2.btcs.network/api" }

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
